config/routes.rb
JuggApp::Application.routes.draw do
  resource :admin, :controller => 'admin', :only => [:show]

  resources :applications, :controller => :applicants, :except => [:show, :destroy] do
    post :post, :on => :member
  end

  resource :user_session, :only => [:new, :create, :destroy]

  match "/login" => "user_sessions#new"

  match "/logout" => "user_sessions#destroy", :method => :delete

  root :to => "applicants#index"
end

app/models/applicant.rb
require 'xmlrpc/client'

# Raised when an application could not be posted for an unknown reason.
class ApplicationGenericError < StandardError
  def initialize
    super "Your application could not be posted at this time."
  end
end

# Raised when attemping to post an application owned by a user who already has one posted.
class ApplicationAlreadyPostedError < StandardError
  def initialize
    super "You cannot have more than one application posted at a time. Please wait for us to review the previous application."
  end
end

# Raised when attempting to do something status-dependent with an invalid status
class ApplicationStatusError < StandardError
  def initialize(msg)
    super msg
  end
end

class Applicant < ActiveRecord::Base
  attr_protected :id, :status, :topic_id, :created_at, :updated_at

  scope :pending,  where(:status => 'pending')
  scope :posted,   where(:status => 'posted')
  scope :denied,   where(:status => 'denied')
  scope :accepted, where(:status => 'accepted')
  scope :guilded,  where(:status => 'guilded')
  scope :waiting,  where(:status => 'waiting')

  WOW_CLASSES = (['Death Knight'] + %w(Druid Hunter Mage Paladin Priest Rogue Shaman Warlock Warrior)).sort.freeze
  WOW_RACES   = (['Blood Elf', 'Night Elf'] + %w(Draenei Dwarf Gnome Goblin Human Orc Tauren Troll Undead Worgen)).sort.freeze

  validates_inclusion_of :status, :in => %w(pending posted denied accepted guilded waiting)
  validates_presence_of :user_id
  # validates_format_of :armory_link, :with => /^http:\/\/(www\.)?wowarmory\.com.+/, :message => 'is not a valid Armory link'
  validates_presence_of :character_name
  validates_presence_of :server
  validates_presence_of :character_race
  validates_inclusion_of :character_race, :in => WOW_RACES, :message => "%{value} is not a valid race", :if => Proc.new { |c| c.character_race.present? }
  validates_presence_of :character_class
  validates_inclusion_of :character_class, :in => WOW_CLASSES, :message => "%{value} is not a valid class", :if => Proc.new { |c| c.character_class.present? }
  validates_presence_of :armory_link
  validates_format_of :screenshot_link, :with => %r{\Ahttps?://}, :allow_nil => true, :allow_blank => true,
    :message => %{is not a URL. Upload your image to a service like <a href="http://imgur.com/" target="_new">imgur</a>.}

  belongs_to :user
  belongs_to :server

  alias_method :current_server, :server

  # Define `[start|end]_[day_of_week]_string` methods for use by Formtastic
  %w(sunday monday tuesday wednesday thursday friday saturday).each do |day|
    %w(start end).each do |type|
      define_method(:"#{type}_#{day}_string") do
        obj = self.send("#{type}_#{day}")
        obj.strftime("%H:%M") unless obj.nil?
      end

      define_method(:"#{type}_#{day}_string=") do |value|
        self.send("#{type}_#{day}=", value)
      end
    end
  end

  def to_s
    return '' unless self.character_name.present? and self.character_class.present? and self.created_at.present?

    "#{self.character_name} - #{self.character_class} - #{self.created_at.to_date.to_s(:db)}"
  end

  # Posts the application through IP.Board's XMLRPC interface
  #
  # Requires <tt>body</tt> to be passed in through the controller's <tt>render_to_string</tt> method.
  #
  # Raises:
  # - ApplicationStatusError unless the application is pending
  # - ApplicationAlreadyPostedError if there is already an application from this user marked as 'posted'
  # - ApplicationGenericError if the application could not be posted for some other reason
  # --
  # TODO: Move XMLRPC stuff to its own model
  def post(body)
    raise ApplicationStatusError.new("Only pending applications may be posted.") unless self.status == 'pending'
    raise ApplicationAlreadyPostedError.new unless self.class.count(:conditions => {:user_id => self.user_id, :status => 'posted'}) == 0

    server = XMLRPC::Client.new2(Juggernaut[:ipb_api_url])

    response = server.call('postTopic', {
      :api_module   => 'ipb',
      :api_key      => Juggernaut[:ipb_api_key],
      :member_field => 'id',
      :member_key   => self.user_id,
      :forum_id     => 6,
      :topic_title  => self.to_s,
      :post_content => body
    })

    if response_valid?(response)
      response.symbolize_keys!
      self.topic_id = response[:topic_id].to_i
      self.status = 'posted'
      self.save
    else
      raise ApplicationGenericError.new
    end
  end

  # Creates a public feedback thread for the applicant through IP.Board's XLMRPC interface
  #
  # Raises:
  # - ApplicationStatusError unless the application is accepted
  # --
  # TODO: Move XMLRPC stuff to its own model
  def create_feedback
    raise ApplicationStatusError.new("Cannot create feedback for an applicant that hasn't been accepted.") unless self.status == 'accepted'

    server = XMLRPC::Client.new2(Juggernaut[:ipb_api_url])

    response = server.call('postTopic', {
      :api_module   => 'ipb',
      :api_key      => Juggernaut[:ipb_api_key],
      :member_field => 'id',
      :member_key   => self.user_id,
      :forum_id     => 50,
      :topic_title  => "#{self.character_name} - #{self.character_class}",
      :post_content => "Public feedback thread for #{self.character_name}."
    })

    # TODO: Response handling? Do we care?
    # if response_valid?(response)
    # else
    # end
  end

  # Given a +Hash+ representing a response from +XMLRPC+, update the +status+ attribute depending on several factors.
  #
  # - A pinned topic in forum 6 (Applicant Review) is considered 'accepted'
  # - A topic in forum 21 (Archives) is considered 'guilded'
  # - A topic in forum 45 (Declined) is considered 'declined'
  # - A topic in forum 44 (Waiting) is considered 'waiting'
  # - 'pending' and 'posted' are controlled by the user and should not be updated here.
  def update_status_from_board!(response)
    return if self.status == 'pending'

    response.symbolize_keys!
    return unless response[:topic_id].present? and response[:topic_id].to_i == self.topic_id

    if response[:pinned].to_i == 1 and response[:forum_id].to_i == 6
      self.status = 'accepted'
    elsif response[:forum_id].to_i == 45
      self.status = 'denied'
    elsif response[:forum_id].to_i == 44
      self.status = 'waiting'
    elsif response[:forum_id].to_i == 21
      self.status = 'guilded'
    end

    self.save
  end

  private

  after_update :check_status_changed

  def check_status_changed
    if self.changed.include? 'status'
      if self.changes['status'][0] == 'posted' and self.status == 'accepted'
        self.create_feedback
      end
    end
  end

  def response_valid?(response)
    response.symbolize_keys!
    response[:result].present? and
    response[:result] == 'success' and
    response[:topic_id].present?
  end
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_filter :require_user
  before_filter :find_parent
  before_filter :find_applicant, :only => [:edit, :update, :post]

  def index
    @applicants = @parent.applicants.order('updated_at DESC')

    respond_to do |wants|
      wants.html
    end
  end

  def new
    @applicant = @parent.applicants.new

    respond_to do |wants|
      wants.html
    end
  end

  def edit
    unless @applicant.status == 'pending'
      flash.now[:error] = "This application has already been posted for review. Changes made here will not be reflected on the posted application."
    end

    respond_to do |wants|
      wants.html
    end
  end

  def create
    @applicant = @parent.applicants.new(params[:applicant])

    respond_to do |wants|
      if @applicant.save
        flash[:message] = 'Application submitted successfully.'
        wants.html { redirect_to root_path }
      else
        flash.now[:error] = "There was a problem with your application. Please see the error messages below."
        wants.html { render :action => "new" }
      end
    end
  end

  def update
    respond_to do |wants|
      if @applicant.update_attributes(params[:applicant])
        flash[:success] = 'Application updated successfully.'
        wants.html { redirect_to root_path }
      else
        flash.now[:error] = "There was a problem with your application. Please see the error messages below."
        wants.html { render :action => 'edit' }
      end
    end
  end

  def post
    begin
      @applicant.post(render_to_string(:layout => false))
      flash[:success] = "Your application has been successfully posted for review."
    rescue ApplicationGenericError, ApplicationStatusError, ApplicationAlreadyPostedError => e
      flash[:error] = e.message
    ensure
      # FIXME: Redirects back to root even though sometimes we want to redirect back to admin
      respond_to do |wants|
        wants.html { redirect_to root_path }
      end
    end
  end

  protected
    def find_parent
      @parent = @user = current_user
    end

    def find_applicant
      if current_user.is_admin?
        @applicant = Applicant.find(params[:id])
      else
        @applicant = @parent.applicants.find(params[:id])
      end
    end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
  def class_icon(klass)
    klass.gsub!(' ', '')

    "classes/#{klass}.png"
  end

  def character_icon(race, klass)
    race.downcase!
    klass.downcase!

    # Base
    str = "http://www.wowarmory.com/_images/portraits/wow-80/"

    # Sex
    str += '0-' # TODO: Females are '1-'

    # Race ID
    str += case race
    when 'human'
      '1'
    when 'orc'
      '2'
    when 'dwarf'
      '3'
    when 'night elf'
      '4'
    when 'undead'
      '5'
    when 'tauren'
      '6'
    when 'gnome'
      '7'
    when 'troll'
      '8'
    when 'blood elf'
      '10'
    when 'dranei'
      '11'
    else
      '0'
    end
    str += '-'

    # Class ID
    str += case klass
    when 'warrior'
      '1'
    when 'paladin'
      '2'
    when 'hunter'
      '3'
    when 'rogue'
      '4'
    when 'priest'
      '5'
    when 'death knight'
      '6'
    when 'shaman'
      '7'
    when 'mage'
      '8'
    when 'warlock'
      '9'
    when 'druid'
      '11'
    else
      '0'
    end

    str += '.gif'

    str
  end

  def play_time_for_day(app, day)
    day.downcase!

    format = "%I:%M %p"
    pstart = app.attributes["start_#{day}"].strftime(format)
    pend   = app.attributes["end_#{day}"].strftime(format)

    "#{pstart} until #{pend} CST #{day.titlecase}"
  rescue
    "N/A until N/A CST #{day.titlecase}"
  end
end

app/views/applicants/_form.html.haml
= form.inputs 'Personal Information' do
  = form.input :name, :label => 'First name', :hint => 'Your real first name', :input_html => {:size => 25}
  = form.input :age, :input_html => {:size => 8}
  = form.input :time_zone, :selected => "Central Time (US & Canada)"
  = form.inputs :name => 'Play times', :class => 'playtimes' do
    %p.inline-hints List the hours you can normally play each day of the week. Mal'Ganis is a Central Standard Time (CST) server.
    - %w(sunday monday tuesday wednesday thursday friday saturday).each do |day|
      .playtimes
        = form.input "start_#{day}_string", :as => :string, :label => '', :required => false, :input_html => {:size => 8}
        %li until
        = form.input "end_#{day}_string", :as => :string, :label => '', :required => false, :input_html => {:size => 8}
        %li= "CST #{day.titlecase}"
  = form.input :known_members, :label => 'List any current Juggernaut members you know and how you know them', :input_html => {:size => '90x15'}
  = form.input :future_commitments, :label => 'List any current or near future commitments you have that might affect your raid attendance', :input_html => {:size => '90x15'}
  = form.input :reasons_for_joining, :label => 'Why do you want to join Juggernaut?', :input_html => {:size => '90x15'}

= form.inputs 'Character Information' do
  = form.input :server, :label => 'Current server', :required => true, :hint => "Note: US servers only."
  = form.input :character_name, :label => 'Current name', :required => true
  = form.input :character_class, :as => :select, :collection => Applicant::WOW_CLASSES, :label => 'Class', :required => true
  = form.input :character_race, :as => :select, :collection => Applicant::WOW_RACES, :label => 'Current race', :required => true
  = form.input :armory_link, :label => "Provide a link to your character's Armory profile", :required => true, :input_html => {:size => 92}
  = form.input :primary_spec, :label => "What is your primary talent spec?"
  = form.input :secondary_spec, :label => "Describe your experience with your off-specs", :input_html => {:size => '90x15'}
  = form.input :previous_guilds, :label => 'Describe, in detail, your entire guild history across all of your characters, and your reasons for leaving each guild', :input_html => {:size => '90x15'}
  = form.input :pve_experience, :label => 'Describe your previous PvE experience', :input_html => {:size => '90x15'}
  = form.input :pvp_experience, :label => 'Describe your previous PvP experience', :input_html => {:size => '90x15'}
  = form.input :screenshot_link, :label => 'Provide a link to a screenshot of your interface during a raid', :input_html => {:size => 92}
  = form.input :logs, :label => 'Provide links to your World of Logs', :input_html => {:size => '90x15'}

= form.inputs :name => 'Additional Comments' do
  = form.input :comments, :label => 'Add any additional information you think may be pertinent', :input_html => {:size => '90x15'}

= form.buttons :class => 'submit' do
  = form.submit 'Save', :class => 'input_submit'
  or
  = link_to('Cancel', root_path, :class => 'cancel')

app/views/applicants/_status_accepted.html.haml
%div.status_info
  %strong Accepted:
  Congratulations! Your application has been accepted for a trial period. You should receive a
  = link_to('private message', 'http://www.juggernautguild.com/index.php?app=members&module=messaging')
  shortly with more information.

app/views/applicants/_status_denied.html.haml
%div.status_info
  %strong Denied:
  Your application has been marked as denied. Thank you for taking the time to apply.

app/views/applicants/_status_guilded.html.haml
%div.status_info
  %strong Guilded:
  You've completed your trial period successfully and are now a full member of Juggernaut. Congratulations! There's nothing left to do here. Go away.

app/views/applicants/_status_pending.html.haml
%div.status_info
  %strong Pending:
  Your application <strong>has not yet been posted</strong> for review. You can
  = link_to('revise it', edit_application_path(app.id))
  or
  = link_to('post it for review', post_application_url(app), :method => :post, :confirm => "Are you sure? Once an application is posted it cannot be edited.") + "."
  %strong Once an application is posted you will not be able to edit it.

app/views/applicants/_status_posted.html.haml
%div.status_info
  %strong Posted:
  Your application has been posted to the private forums for review by Juggernaut members and officers. There's nothing left to do now but wait for a response.

app/views/applicants/_status_waiting.html.haml
%div.status_info
  %strong Waiting:
  Your application was acceptable but unfortunately we don't currently have a spot available for you. Please check back in case one opens up.

app/views/applicants/edit.html.haml
- page_title 'Edit Application'
- breadcrumb link_to('Applications', root_path), h(@applicant.character_name), 'Edit'
= semantic_form_for @applicant, :url => application_path(@applicant) do |form|
  = render :partial => 'form', :object => form

app/views/applicants/index.html.haml
- page_title 'My Applications'
- breadcrumb 'My Applications'
%div.category_block.block_wrap
  = render :partial => 'shared/maintitle', :object => "Applications"
  - @applicants.each do |app|
    %div{ :class => "character_row status_#{app.status}" }
      = image_tag(class_icon(app.character_class), :alt => "Icon", :class => 'character_image')
      %div.application_status
        = image_tag("status_#{app.status}.png", :alt => app.status.titlecase)
      %div.application_info
        %div.applicant_name
          %h4= link_to(h(app.character_name), edit_application_path(app))
        = render :partial => "status_#{app.status}", :locals => { :app => app }

%fieldset.submit= link_to('Submit New Application', new_application_path, :class => 'input_submit')
%br.clear

app/views/applicants/new.html.haml
- page_title 'New Application'
- breadcrumb link_to('Applications', root_path), 'New Application'
= semantic_form_for @applicant, :url => applications_path do |form|
  = render :partial => 'form', :object => form

app/views/applicants/post.erb
[b][size="4"]Personal Info[/size][/b]

[b]First name[/b]
<%= raw @applicant.name %>

[b]Age[/b]
<%= raw @applicant.age %>

[b]Time zone[/b]
<%= raw @applicant.time_zone %>

[b]Play times[/b]
<%- %w(sunday monday tuesday wednesday thursday friday saturday).each do |day| -%>
<%= play_time_for_day(@applicant, day) %>
<%- end -%>

[b]List any current Juggernaut members you know and how you know them[/b]
<%= raw @applicant.known_members %>

[b]List any current or near future commitments you have that might affect your raid attendance[/b]
<%= raw @applicant.future_commitments %>

[b]Why do you want to join Juggernaut?[/b]
<%= raw @applicant.reasons_for_joining %>

[b][size="4"]Character Information[/size][/b]

[b]Current server[/b]
<%= raw @applicant.server.name %>

[b]Current name[/b]
<%= raw @applicant.character_name %>

[b]Class[/b]
<%= raw @applicant.character_class %>

[b]Current race[/b]
<%= raw @applicant.character_race %>

[b]Armory link[/b]
[url="<%= raw @applicant.armory_link %>"]<%= raw @applicant.armory_link %>[/url]

[b]What is your primary talent spec?[/b]
<%= raw @applicant.primary_spec %>

[b]Describe your experience with your off-specs[/b]
<%= raw @applicant.secondary_spec %>

[b]Describe, in detail, your entire guild history across all of your characters, and your reasons for leaving each guild[/b]
<%= raw @applicant.previous_guilds %>

[b]Describe your previous PvE experience[/b]
<%= raw @applicant.pve_experience %>

[b]Describe your previous PvP experience[/b]
<%= raw @applicant.pvp_experience %>

[b]Provide a link to a screenshot of your interface during a raid[/b]
<%- if @applicant.screenshot_link.present? -%>
<%= raw @applicant.screenshot_link %>
<%- end -%>

[b]Provide links to your World of Logs[/b]
<%= raw @applicant.logs %>

[b][size="4"]Additional Comments[/size][/b]

<%= raw @applicant.comments %>